### PR TITLE
fix: multistream-select negotiation on outbound substream over webrtc

### LINKED ISSUE #464: webrtc: multistream-select negotiation not fully spec compliant
I'm testing interoperability between a smoldot dialer running in wasm/Chrome and a litep2p listener. Right now this is limited to connection establishment, noise handshake and ping behaviour in either direction. The only part that doesn't work is multistream-select negotiation on the outbound substream from litep2p to smoldot.

Due to the libp2p-webrtc specific protobuf framing and how network data is surfaced by str0m, there is [a custom code path](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/transport/webrtc/connection.rs#L374) for handling multistream-select negotiation on webrtc connections. That code path does not use [`multistream_select::protocol::MessageIO`](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/multistream_select/protocol.rs#L260) by going through [`listener_select_proto()`](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/multistream_select/listener_select.rs#L57) and therefore does not handle length prefixes in multistream-select messages correctly.

When smoldot is made aware of a newly opened inbound substream by calling [`MultiStream::add_substream()`](https://github.com/smol-dot/smoldot/blob/33d34fb8733c7d8a7e5878f8658bc7a0d0383bae/lib/src/libp2p/connection/established/multi_stream.rs#L192), it [sends the multistream-select header right away](https://github.com/smol-dot/smoldot/blob/33d34fb8733c7d8a7e5878f8658bc7a0d0383bae/lib/src/libp2p/connection/multistream_select.rs#L209), without waiting for any data to arrive from the dialer. The resulting message only contains the header, [with a length prefix](https://github.com/smol-dot/smoldot/blob/33d34fb8733c7d8a7e5878f8658bc7a0d0383bae/lib/src/libp2p/connection/multistream_select.rs#L398).

Once the protocol request message has been received from the dialer and the API user has accepted the protocol, [the confirmation message is sent](https://github.com/smol-dot/smoldot/blob/33d34fb8733c7d8a7e5878f8658bc7a0d0383bae/lib/src/libp2p/connection/multistream_select.rs#L133).

The `Vec<u8>` [received from str0m in the `ChannelData` event](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/transport/webrtc/connection.rs#L732) still contains the length prefix, which causes the relevant comparisons in `multistream_select::protocol::Message::decode()` to fail [for the header](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/multistream_select/protocol.rs#L176) and the [protocol confirmation](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/multistream_select/protocol.rs#L190).

When litep2p is the listener, the negotiation succeeds, because <strike>litep2p sends both header and protocol confirmation in one message, which `multistream_select::protocol::Message::encode()` treats as response to an `ls` command and [adds length prefixes](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/multistream_select/protocol.rs#L153)</strike> [`webrtc_encode_multistream_message()`](https://github.com/paritytech/litep2p/blob/1e3fa87bc2dd143f8a4390582a4539e10a17eae0/src/multistream_select/protocol.rs#L235) adds length prefixes.

### PR DESCRIPTION
**Pull request by haikoschol**
This PR changes how multistream-select messages received on an opening outbound substream are handled on webrtc connections. For details please see the issue description.

The PR builds on top of #441 for the str0m update. But looking at it again I realized that it also made changes to multistream-select handling. I'll look into what those are and how they relate to my changes. In any case, I believe my changes bring the implementation closer to compliance with the multistream-select spec and enable interoperability with smoldot.

fixes #464

### CODE REVIEW

File: src/transport/webrtc/connection.rs [hunk 1]
```diff
@@ -631,6 +642,8 @@ impl WebRtcConnection {
             protocol: protocol.to_string(),
         });
 
+        // self.rtc.channel(channel_id).unwrap().set_buffered_amount_low_threshold(1024);
```
Comment (haikoschol) [inline src/transport/webrtc/connection.rs]: This is [an unrelated issue](https://github.com/paritytech/litep2p/pull/441#discussion_r2464955120).

File: src/transport/webrtc/connection.rs [hunk 2]
```diff
@@ -787,17 +814,15 @@ impl WebRtcConnection {
                 },
                 event = self.handles.next() => match event {
                     None => unreachable!(),
-                    Some((channel_id, None | Some(SubstreamEvent::Close))) => {
+                    Some((_, None)) => {}
```
Comment (haikoschol) [inline src/transport/webrtc/connection.rs]: This is a superficial fix for another unrelated issue which I haven't investigated yet. Without this change, a "channel closed" event is fired repeatedly after a while. I believe this is caused by `SubstreamHandle::tx` being dropped, presumably when the substream(/channel?) is closed. The fact that the event continues firing suggests that `SubstreamHandle::rx` continues to be polled. Maybe the handle simply needs to be removed from `self.handles`?

I've also seen this happen when briefly testing with a rust-libp2p dialer, so this is not related to smoldot interop.

File: src/transport/webrtc/connection.rs [hunk 3]
```diff
@@ -787,17 +814,15 @@ impl WebRtcConnection {
...
                         tracing::trace!(
                             target: LOG_TARGET,
                             peer = ?self.peer,
                             ?channel_id,
                             "channel closed",
                         );
-
-                        self.rtc.direct_api().close_data_channel(channel_id);
                         self.channels.insert(channel_id, ChannelState::Closing);
-                        self.handles.remove(&channel_id);
```
Comment (lexnv) [inline src/transport/webrtc/connection.rs:800]: Wouldn't this lead to memory leaks due to keeping the channel ids around? 🤔

Comment (haikoschol) [reply src/transport/webrtc/connection.rs:800]: You are right. I don't remember what exactly I had in mind with that change. Probably expecting that `Event::ChannelClose` would be emitted eventually and `Connection::on_channel_closed()` called, which does the full cleanup. But that's not exactly how it works.

The way it was before is incorrect as well, but that's out of scope for this PR since it is related with signaling of substream closure via the WebRTC protobuf frame.
Anyway, I'll revert this change and we'll revisit it in a follow-up PR.

File: src/transport/webrtc/connection.rs (hunk 1 above)
Comment (haikoschol) [reply src/transport/webrtc/connection.rs]: I've removed this line since it is unrelated to this PR and should be address later when working on [backpressure](https://github.com/paritytech/litep2p/issues/45).

File: src/transport/webrtc/connection.rs (hunk 2 above)
Comment (haikoschol) [reply src/transport/webrtc/connection.rs]: I just tested again without this change and now I don't get repeating "channel closed" messages in the logs. Presumably this is due to a change somewhere else that I can't pin down right now. In any case, it was unrelated to multistream-select negotiation.

File: src/multistream_select/dialer_select.rs [hunk 4]
```diff
@@ -41,6 +41,7 @@ use std::{
     pin::Pin,
     task::{Context, Poll},
 };
+use crate::error::SubstreamError;
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: nit: We could group it with the previous crate import

File: src/multistream_select/dialer_select.rs [hunk 5]
```diff
@@ -357,23 +358,67 @@ impl WebRtcDialerState {
...
-                NegotiationError::Failed,
-            ));
+        let header = Protocol::try_from(&b"/multistream/1.0.0"[..])
+            .expect("valid multitstream-select header");
+
+        // All multistream-select messages are length-prefixed. Since this code path is not using
+        // multistream_select::protocol::MessageIO, we need to decode and remove the length here.
+        let mut remaining: &[u8] = &payload;
+        let (len, tail) = unsigned_varint::decode::usize(remaining).
+            map_err(|_| error::NegotiationError::ParseError(ParseError::InvalidData))?;
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: nit: Let's log a degub about about this error, decoding usize should pass in most of the cases

File: src/multistream_select/dialer_select.rs [hunk 6]
```diff
@@ -357,23 +358,67 @@ impl WebRtcDialerState {
...
+
+        let payload = tail[..len].to_vec();
+
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: nit: It would be good if we can greak the code such that we provide better trace logging:

```rust
let message = Message::decode(payload.into());

tracing::trace!(
    target: LOG_TARGET,
    ?message,
    "Decoded message while registering response",
);

let mut protocols = match message {
    ..
};

```

Let me know if this makes sense or if you think it will polute too much the logs

File: src/multistream_select/dialer_select.rs [hunk 7]
```diff
@@ -357,23 +358,67 @@ impl WebRtcDialerState {
...
 
+        remaining = &tail[len..];
+
+        loop {
+            if remaining.is_empty() {
+                break;
+            }
+
+            let (len, tail) = unsigned_varint::decode::usize(remaining).
+                map_err(|_| error::NegotiationError::ParseError(ParseError::InvalidData))?;
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: Does this mean we are expecting multiple `[ len_prefix ++ Message ]` to arrive from the `register_response` of the WebRTC?

Who would normally exhibit this behavior (libp2p or smoldot)?

File: src/multistream_select/dialer_select.rs [hunk 8]
```diff
@@ -357,23 +358,67 @@ impl WebRtcDialerState {
...
+
+            if len > tail.len() {
+                break;
+            }
+
+            let payload = tail[..len].to_vec();
+
+            match Message::decode(payload.into()) {
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: nit: Lets log in a smilar way the message here, the `_` is too loose and it might help us debug connectivity issues

File: src/multistream_select/dialer_select.rs [hunk 9]
```diff
@@ -357,23 +358,67 @@ impl WebRtcDialerState {
...
+                    _ => Err(error::NegotiationError::StateMismatch),
+                }
+            }
+            Ok(Message::ListProtocols) => return Err(error::NegotiationError::StateMismatch),
+            Err(_) => return Err(error::NegotiationError::ParseError(ParseError::InvalidData)),
         };
 
+        remaining = &tail[len..];
+
+        loop {
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: nit: We can move this to a dedicated fn `drain_trailing_protocols`. Then, we can add tests for this behavior to enure we are not missing other frames and we receive expected errors.

Is this spec compliant? It seems like some hoops we have to jump through to make either libp2p/smoldot happy

File: src/multistream_select/dialer_select.rs [hunk 10]
```diff
@@ -357,23 +358,67 @@ impl WebRtcDialerState {
         &mut self,
         payload: Vec<u8>,
     ) -> Result<HandshakeResult, crate::error::NegotiationError> {
-        let Message::Protocols(protocols) =
-            Message::decode(payload.into()).map_err(|_| ParseError::InvalidData)?
-        else {
-            return Err(crate::error::NegotiationError::MultistreamSelectError(
-                NegotiationError::Failed,
-            ));
+        let header = Protocol::try_from(&b"/multistream/1.0.0"[..])
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: nit: Could add a const about this similar to `MSG_MULTISTREAM_1_0`

File: src/multistream_select/dialer_select.rs [hunk 11]
```diff
@@ -755,23 +802,18 @@ mod tests {
...
-        };
+        let mut bytes = BytesMut::with_capacity(32);
+        bytes.put_u8(MSG_MULTISTREAM_1_0.len() as u8);
+        let _ = Message::Header(HeaderLine::V1).encode(&mut bytes).unwrap();
+
+        let proto = Protocol::try_from(&b"/13371338/proto/1"[..]).expect("valid protocol name");
+        bytes.put_u8((proto.as_ref().len() + 1) as u8); // + 1 for \n
+        let _ = Message::Protocol(proto).encode(&mut bytes).unwrap();
+
+        let expected_message = bytes.freeze().to_vec();
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs:806]: dq: This slightly changes the meaning of the messages.

Before we were expecting: 

```
[Protocols(/multistream/1.0.0), Protocol(/13371338/proto/1)]
```

Now we are expecting:

```
// \n added
[Header(/multistream/1.0.0 /\n),

// \n counted but not checked
Protocol(/13371338/proto/1 [])
```

Hmm, one of those representation can't be spec compliant right? 

Also are we ignoring malformated messages:
- we decode the frame size correctly
- but we don't check then if the last character is `\n` or not sufficeint bytes provided?

**Review by lexnv — COMMENTED** [review]
Great job so far! Feels like we are getting closer to figuring out the multistream select 🙏 

My questions revolve around the spec correctness of the implementation, or if we basically implemented a tiny subset in the past? And mainly, which implementation is causing us to extensively parse the frames (libp2p or smoldot or both?) 🤔

File: src/multistream_select/dialer_select.rs (hunk 6 above)
Comment (haikoschol) [reply src/multistream_select/dialer_select.rs]: I think this is fine, especially as a trace.

File: src/multistream_select/dialer_select.rs (hunk 9 above)
Comment (haikoschol) [reply src/multistream_select/dialer_select.rs]: I've extracted the loop to a function, but I don't know what you mean with "not missing other frames". The code is covered by some of the existing tests (`negotiate_main_protocol()` and `negotiate_fallback_protocol()` IIRC).

The reason for adding this loop is that I removed a line in `webrtc_encode_multistream_message()` that [adds a newline at the end](https://github.com/paritytech/litep2p/pull/465/files#diff-d546bf98df892f7b9165971703a8e8c521913a7c5c4c8ae9c1c501949ddfe263L253). What isn't spec compliant is adding this newline, because that is only present in an "ls response" (even with the newline it is not a valid "ls response" because it lacks a length-prefix for the total message size at the start). It worked before because smoldot and rust-libp2p tolerate this extra newline.

Comment (lexnv) [reply src/multistream_select/dialer_select.rs]: Got it! Makes perfect sense! Thanks @haikoschol again for handling this 🙏

File: src/multistream_select/dialer_select.rs [hunk 12]
```diff
@@ -358,20 +357,32 @@ impl WebRtcDialerState {
         &mut self,
         payload: Vec<u8>,
     ) -> Result<HandshakeResult, crate::error::NegotiationError> {
-        let header = Protocol::try_from(&b"/multistream/1.0.0"[..])
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: Nit: Before we were constructing the protocol from `b"/multistream/1.0.0"`. Now we are using `pub const MSG_MULTISTREAM_1_0: &[u8] = b"/multistream/1.0.0\n";` which adds the extra `\n`.

This should be fine as long as we don't add an extra `\n` at the end: https://github.com/paritytech/litep2p/pull/465/files#diff-d546bf98df892f7b9165971703a8e8c521913a7c5c4c8ae9c1c501949ddfe263L253?

Comment (haikoschol) [reply src/multistream_select/dialer_select.rs]: Yes, the line that adds the `\n` is problematic for reasons I've tried to explain [here](https://github.com/paritytech/litep2p/pull/465#discussion_r2523177188).

The result we want from `webrtc_encode_multistream_message()` is a single WebRTC protobuf frame that contains one or more multistream messages.

`Message::encode()` adds a newline when encoding `Message::Protocol`, so if we add another one in `webrtc_encode_multistream_message()`, the result is not spec-compliant.

File: src/multistream_select/dialer_select.rs (hunk 11 above)
Comment (haikoschol) [reply src/multistream_select/dialer_select.rs:806]: Right now the test ensures that the wire format that `WebRtcDialerState::propose()` produces is what we expect. Before it actually ensured that whatever `propose()` produces can be decoded with `Message::decode()`. So I did change the semantics of the test after all. But I would argue that the new meaning is more useful. We could also add decoding and assert we get the expected strings back, but due to the changes made, this can no longer be done by just calling `Message::decode()`.

File: src/multistream_select/dialer_select.rs [hunk 13]
```diff
@@ -405,12 +441,62 @@ impl WebRtcDialerState {
...
+                tracing::debug!(
+                    target: LOG_TARGET,
+                    ?error,
+                    message = ?remaining,
+                    "Failed to decode length-prefix in multistream message");
+                error::NegotiationError::ParseError(ParseError::InvalidData)
+            })?;
+
+        if len > tail.len() {
+            break;
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs]: nit: I think this would miss a few protocols, maybe return an error and add a debug log?

Comment (haikoschol) [reply src/multistream_select/dialer_select.rs]: I just tried this and it caused the test [`header_line_missing()`](https://github.com/ChainSafe/litep2p/blob/9621e3ccda915882f0dc93b7c2ea46c80c0fea7a/src/multistream_select/dialer_select.rs#L902) to fail. This is because that test used `Message::Protocols` to encode two protocol names (without a header) to use as a negotiation response. This isn't spec compliant in two ways that are irrelevant to what is being tested, so I changed the test to send one protocol name.

File: src/multistream_select/dialer_select.rs [hunk 14]
```diff
@@ -357,24 +357,57 @@ impl WebRtcDialerState {
...
+                    target: LOG_TARGET,
+                    ?error,
+                    message = ?payload,
+                    "Failed to decode length-prefix in multistream message");
+            error::NegotiationError::ParseError(ParseError::InvalidData)
+        })?;
+
+        let payload = tail[..len].to_vec();
+
+        let message = Message::decode(payload.into());
```
Comment (dmitry-markin) [inline src/multistream_select/dialer_select.rs]: nit: to not allocate & copy the data we can wrap the original `Vec<u8>` data into `Bytes` directly and then slice this new `Bytes` object into other `Bytes` chunks to pass to `Message::decode` here and later in `drain_trailing_protocols`:

```suggestion
        let len_size = remaining.len() - tail.len();
        let bytes = Bytes::from(payload);
        let payload = bytes.slice(len_size..len_size + len);
        let remaining = bytes.slice(len_size + len..);
        
        let message = Message::decode(payload);
```

File: src/multistream_select/dialer_select.rs [hunk 15]
```diff
@@ -405,10 +438,66 @@ impl WebRtcDialerState {
     }
 }
 
+fn drain_trailing_protocols(
+    tail: &[u8],
+    len: usize,
+) -> Result<Vec<Protocol>, error::NegotiationError> {
+    let mut protocols = vec![];
+    let mut remaining = &tail[len..];
```
Comment (dmitry-markin) [inline src/multistream_select/dialer_select.rs]:
```suggestion
fn drain_trailing_protocols(
    mut remaining: Bytes,
) -> Result<Vec<Protocol>, error::NegotiationError> {
    let mut protocols = vec![];
```

File: src/multistream_select/dialer_select.rs [hunk 16]
```diff
@@ -357,24 +357,57 @@ impl WebRtcDialerState {
...
+                    HandshakeState::WaitingProtocol => Err(
+                        error::NegotiationError::MultistreamSelectError(NegotiationError::Failed),
+                    ),
+                    _ => Err(error::NegotiationError::StateMismatch),
+                },
+            Ok(Message::ListProtocols) => return Err(error::NegotiationError::StateMismatch),
+            Err(_) => return Err(error::NegotiationError::ParseError(ParseError::InvalidData)),
         };
 
+        match drain_trailing_protocols(tail, len) {
```
Comment (dmitry-markin) [inline src/multistream_select/dialer_select.rs]:
```suggestion
        match drain_trailing_protocols(remaining) {
```

File: src/multistream_select/dialer_select.rs [hunk 17]
```diff
@@ -405,10 +438,66 @@ impl WebRtcDialerState {
...
+                actual_length = tail.len(),
+                "Truncated multistream message",
+            );
+
+            return Err(error::NegotiationError::ParseError(ParseError::InvalidData));
+        }
+
+        let payload = tail[..len].to_vec();
+
+        match Message::decode(payload.into()) {
```
Comment (dmitry-markin) [inline src/multistream_select/dialer_select.rs]:
```suggestion
        let len_size = remaining.len() - tail.len();
        let payload = remaining.slice(len_size..len_size + len);

        match Message::decode(payload) {
```

File: src/multistream_select/dialer_select.rs [hunk 18]
```diff
@@ -405,10 +438,66 @@ impl WebRtcDialerState {
...
+                    ?error,
+                    message = ?tail[..len],
+                    "Failed to decode multistream message",
+                );
+                return Err(error::NegotiationError::ParseError(ParseError::InvalidData));
+            }
+            _ => return Err(error::NegotiationError::StateMismatch),
+        }
+
+        remaining = &tail[len..];
```
Comment (dmitry-markin) [inline src/multistream_select/dialer_select.rs]:
```suggestion
        remaining = remaining.slice(len_size + len..);
```

File: src/multistream_select/dialer_select.rs [hunk 19]
```diff
@@ -405,10 +438,66 @@ impl WebRtcDialerState {
...
+) -> Result<Vec<Protocol>, error::NegotiationError> {
+    let mut protocols = vec![];
+    let mut remaining = &tail[len..];
+
+    loop {
+        if remaining.is_empty() {
+            break;
+        }
+
+        let (len, tail) = unsigned_varint::decode::usize(remaining).map_err(|error| {
```
Comment (dmitry-markin) [inline src/multistream_select/dialer_select.rs]:
```suggestion
        let (len, tail) = unsigned_varint::decode::usize(&remaining).map_err(|error| {
```

File: src/multistream_select/listener_select.rs [hunk 20]
```diff
@@ -351,6 +351,14 @@ pub fn webrtc_listener_negotiate<'a>(
     supported_protocols: &'a mut impl Iterator<Item = &'a ProtocolName>,
     payload: Bytes,
 ) -> crate::Result<ListenerSelectResult> {
+    let payload = if payload.len() > 2 && payload[0..payload.len() - 2] != b"\n\n"[..] {
```
Comment (dmitry-markin) [inline src/multistream_select/listener_select.rs]: Is there a way around this without allocation? As the comment in `Message::decode` says, the well-formed message is terminated with a newline. Also, why are we checking for two newlines, but are adding one?

File: src/transport/webrtc/connection.rs [hunk 21]
```diff
@@ -742,6 +743,20 @@ impl WebRtcConnection {
 
                         continue;
                     }
+                    Event::ChannelBufferedAmountLow(channel_id) => {
```
Comment (dmitry-markin) [inline src/transport/webrtc/connection.rs]: Are you sure it is safe to rely on this event for closing the channel? Its original purpose seems to suggest to buffer more data, and not all the data might be drained yet.

**Review by dmitry-markin — APPROVED** [review]
Looks good code-wise, but I haven't checked the conformance to the spec.

The only concern is the use of `ChannelBufferedAmountLow` event.

File: src/transport/webrtc/connection.rs (hunk 21 above)
Comment (haikoschol) [reply src/transport/webrtc/connection.rs]: This change was inherited from [the PR/branch I based this on](https://github.com/paritytech/litep2p/pull/441) and is unrelated to the multistream-select negotiation fixes. I'm happy to remove it if you prefer, but note that the channel is only closed when it was already in `ChannelState::Closing`.

How we use `Event::ChannelBufferedAmountLow` (probably in the context of backpressure) and how channels are closed (when correctly handling `FIN` flags, etc) needs to be revisited in any case.

File: src/multistream_select/listener_select.rs (hunk 20 above)
Comment (haikoschol) [reply src/multistream_select/listener_select.rs]: It can be avoided by passing a `BytesMut` to the function. While looking into this, I noticed that there are (failing) tests in this module that I didn't run when working on this PR and then I noticed that the tests are not run in GH Actions either. Is this intentional? (cc @lexnv)

Comment (haikoschol) [reply src/multistream_select/listener_select.rs]: > Also, why are we checking for two newlines, but are adding one?

This is quite messy because we are misusing `Message::Protocols` to parse what is actually two distinct multistream-select messages that are often sent inside one `WebRtcMessage`. I wanted to keep the changes in this PR minimal, knowing that we need to rewrite the listener negotiation anyway to support the "back-and-forth" (as you pointed out in #75).

Comment (haikoschol) [reply src/multistream_select/listener_select.rs]: There is a way to avoid appending a newline and using `Message::Protocols` to decode, by reusing `drain_trailing_protocols()`. I've implemented this in [`c0a44c0 `](https://github.com/ChainSafe/litep2p/commit/c0a44c089c3698242eb752bef6c0f5eea872f328).

I have not retested this with libp2p and smoldot. Will do that tomorrow.

Comment (haikoschol) [reply src/multistream_select/listener_select.rs]: > I have not retested this with libp2p and smoldot. Will do that tomorrow.

### litep2p-perf with a libp2p dialer

works (d/l up to 512KiB, u/l up to 16MiB)

### litep2p-perf with [a smoldot dialer](https://github.com/ChainSafe/smoldot/commits/haiko-webrtc-perf/)

litep2p crashes apparently during the noise handshake:

```
2025-11-27T12:45:32.307986Z DEBUG litep2p::webrtc: received non-stun message source=127.0.0.1:63971

thread 'main' (15158228) panicked at /Users/haiko/code/polkadot/litep2p/src/transport/webrtc/opening.rs:432:70:
to succeed: ParseError(InvalidData)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2025-11-27T12:45:32.308961Z  WARN litep2p::transport-service: transport service closed
2025-11-27T12:45:32.309016Z  WARN litep2p::transport-service: transport service closed
2025-11-27T12:45:32.309022Z  WARN litep2p::transport-service: transport service closed
```

This makes absolutely no sense to me yet. I know that I've tested this before and I haven't made any changes to the smoldot side since. I've tried a few previous commits for litep2p but always had the same result. Need to keep investigating...

### [webrtc-poc](https://github.com/haikoschol/webrtc-poc/blob/haiko-testing/litep2p-server/src/main.rs) with a libp2p dialer

what works:

- noise handshake
- substream opening and multistream-select negotiation from libp2p to litep2p
- ping from libp2p to litep2p

what doesn't work:

- substream opening and multistream-select negotiation from litep2p to libp2p

I thought I had tested this before, but I'm not sure. Maybe I just focused on smoldot. My previous comment [here](https://github.com/paritytech/litep2p/pull/465#issuecomment-3525617599) doesn't mention this pairing either. I've also tried previous commits on this PR branch without success. Need to keep investigating here as well.

### [webrtc-poc](https://github.com/haikoschol/webrtc-poc/blob/haiko-testing/litep2p-server/src/main.rs) with [a smoldot dialer](https://github.com/ChainSafe/smoldot/commits/haiko-libp2p-webrtc)

works

File: src/transport/webrtc/connection.rs (hunk 21 above)
Comment (dmitry-markin) [reply src/transport/webrtc/connection.rs]: Let's remove it and revisit buffering, closing and backpressure in a separate PR.

File: src/multistream_select/listener_select.rs (hunk 20 above)
Comment (haikoschol) [reply src/multistream_select/listener_select.rs]: > ### [webrtc-poc](https://github.com/haikoschol/webrtc-poc/blob/haiko-testing/litep2p-server/src/main.rs) with a libp2p dialer
> what works:
> 
> * noise handshake
> * substream opening and multistream-select negotiation from libp2p to litep2p
> * ping from libp2p to litep2p
> 
> what doesn't work:
> 
> * substream opening and multistream-select negotiation from litep2p to libp2p

I figured out what is going on here and opened #494. The relevant insight in the context of this review is that the faulty behavior is not caused by a regression introduced in this PR.

Comment (haikoschol) [reply src/multistream_select/listener_select.rs]: > ### litep2p-perf with [a smoldot dialer](https://github.com/ChainSafe/smoldot/commits/haiko-webrtc-perf/)
> litep2p crashes apparently during the noise handshake:
> 
> ```
> 2025-11-27T12:45:32.307986Z DEBUG litep2p::webrtc: received non-stun message source=127.0.0.1:63971
> 
> thread 'main' (15158228) panicked at /Users/haiko/code/polkadot/litep2p/src/transport/webrtc/opening.rs:432:70:
> to succeed: ParseError(InvalidData)
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 2025-11-27T12:45:32.308961Z  WARN litep2p::transport-service: transport service closed
> 2025-11-27T12:45:32.309016Z  WARN litep2p::transport-service: transport service closed
> 2025-11-27T12:45:32.309022Z  WARN litep2p::transport-service: transport service closed
> ```
> 
> This makes absolutely no sense to me yet. I know that I've tested this before and I haven't made any changes to the smoldot side since.

I've looked into this issue again and figured out what is going on. I hadn't actually tested this specific combination before (litep2p listener, smoldot dialer, perf behavior). The combinations I tested were:

* libp2p listener, smoldot dialer, perf behavior
* litep2p listener, smoldot dialer, ping in both directions

I have two branches in the ChainSafe smoldot fork; one for the perf behavior ([`haiko-webrtc-perf`](https://github.com/ChainSafe/smoldot/commits/haiko-webrtc-perf/)) and one for ping ([`haiko-libp2p-webrtc`](https://github.com/ChainSafe/smoldot/commits/haiko-libp2p-webrtc)). When I tested the second combination listed above (and found the issue this PR is addressing) I ran into this crash in the noise handshake on the branch `haiko-libp2p-webrtc` and fixed it (or rather avoided it) in [this commit](https://github.com/ChainSafe/smoldot/commit/10db21bc7d1ad07d8e578e637caf3d1ab10520e9). Making the same change on the other branch also avoids this crash.

What happens is that without this fix, smoldot sends a two byte long message (i.e. an incomplete WebRTC protobuf frame), which fails to decode [here](https://github.com/paritytech/litep2p/blob/925caa9dac387fff250ec1bfcf170b8cefd57be7/src/transport/webrtc/opening.rs#L256) and panics due to an `.expect()` [here](https://github.com/paritytech/litep2p/blob/925caa9dac387fff250ec1bfcf170b8cefd57be7/src/transport/webrtc/opening.rs#L432).

In short, this crash is not a regression caused by the changes in this PR.

Comment (haikoschol) [reply src/multistream_select/listener_select.rs]: @dmitry-markin can you please go through my comments above and resolve this thread if you are happy with the change I made in [c0a44c0](https://github.com/ChainSafe/litep2p/commit/c0a44c089c3698242eb752bef6c0f5eea872f328)?

File: src/multistream_select/dialer_select.rs [hunk 22]
```diff
@@ -357,24 +358,59 @@ impl WebRtcDialerState {
...
         payload: Vec<u8>,
     ) -> Result<HandshakeResult, crate::error::NegotiationError> {
-        let Message::Protocols(protocols) =
-            Message::decode(payload.into()).map_err(|_| ParseError::InvalidData)?
-        else {
-            return Err(crate::error::NegotiationError::MultistreamSelectError(
-                NegotiationError::Failed,
-            ));
+        // All multistream-select messages are length-prefixed. Since this code path is not using
+        // multistream_select::protocol::MessageIO, we need to decode and remove the length here.
```
Comment (lexnv) [inline src/multistream_select/dialer_select.rs:362]:
```suggestion
        // multistream_select::protocol::MessageIO. We need to decode and remove the length here.
```

Comment (lexnv) [reply src/multistream_select/dialer_select.rs:362]: Lets do this or similar, the CI passed but it doesn't allow us to merge your PR, let's retriggerit

Comment (haikoschol) [reply src/multistream_select/dialer_select.rs:362]: I just merged `master` to poke it.
