### PR TITLE
ping: Conform to the spec & exclude from connection keep-alive

### LINKED ISSUE #415: Ping: repeat requests periodically
Currently, ping request is only sent once when a connection is established. As a mechanism of detecting broken connections ping only makes sense if it is repeated periodically. For example, libp2p repeats pings every [15 seconds by default](https://github.com/libp2p/rust-libp2p/blob/e6b0e34733c11c2d6bc165fda2ce22c995e0805d/protocols/ping/src/handler.rs#L66). We need to do the same.

Care should be taken for ping substreams to not keep connections alive if there are no other substreams. See https://github.com/paritytech/litep2p/issues/414 for more info.

### PR DESCRIPTION
**Pull request by dharjeezy**
This PR makes ping protocol conform to the [spec](https://github.com/libp2p/specs/blob/master/ping/ping.md), specifically:
1. Repeat ping requests instead of sending them only on connect.
2. Reuse ping substreams (both inbound and outbound) for subsequent requests, as required by the spec. This is needed for [smoldot](https://github.com/smol-dot/smoldot) compatibility.
3. Exclude ping substreams from the connection keep-alive mechanism, allowing it to close connection on timeout if only ping (and identify) substreams are open.

Tested litep2p-litep2p, litep2p-(pre-PR)litep2p, litep2p-smoldot.

Closes #415

### CODE REVIEW

File: src/protocol/libp2p/ping/mod.rs [hunk 1]
```diff
@@ -192,6 +195,19 @@ impl Ping {
                     Some(_) => {}
                     None => return,
                 },
+                _ = interval.tick() => {
+                    for peer in &self.peers {
+                        tracing::trace!(target: LOG_TARGET, ?peer, "sending ping");
+                        if let Err(error) = self.service.open_substream(*peer) {
```
Comment (dmitry-markin) [inline src/protocol/libp2p/ping/mod.rs]: The libp2p ping protocol spec states that the repeated pings should go on the same substream: https://github.com/libp2p/specs/blob/master/ping/ping.md

Because of this, the issue is actually more difficult due to the need to not keep the connection alive by this ping substream.

I don't think we should break the spec even if it works with the current libp2p implementation. @lexnv what do you think?

Comment (lexnv) [reply src/protocol/libp2p/ping/mod.rs]: Indeed, I would comply with the libp2p spec as much as possible. The main issue would be that we cannot distinguish ping susbtreams for the keep alive connection tracker 🤔 

Are we entirely convinced we need to implement this for ping?
- we'll need to adjust the substream API to expose that the substream is ping (accounting towards the keepalive)
- how do we treat failures here? If we cannot open a substream should we terminate the connection? If so, we need to propagate again to the higher levels the signal to terminate the connection
  - offhand, from ping we'll need to propagate towards the transport manager, and from the transport manager we'll need to propagate to individual connections

**Comment by dharjeezy** [comment]
> > Hey, this is going in the right direction, but there should be a way to simplify the implementation by not introducing separate async tasks for inbound/outbound substreams and not adding command channels. It should be possible to implement polling of inbound substreams by putting them into `FuturesUnordered` or, may be, `tokio_stream::StreamMap`. The latter should be quite easy as there is maximum one inbound substream allowed from any remote peer as per ping spec: https://github.com/libp2p/specs/blob/master/ping/ping.md
> 
> `tokio_stream::StreamMap` might not work because we need to also write to substream and not only poll it, but still there should be a way to simplify the code.

@dmitry-markin can you check my current implementation

**Review by dmitry-markin — COMMENTED** [review]
Hey hey, nice use of `SplitStream`/`SplitSink`! I think what is missing is a cleaner separation between inbound and outbound substreams. On inbound substreams we should only respond to incoming pings, and on outbound send pings ourself. It would be better than relying on the presence of the time in the map, which can get screwed when we both send pings to a peer and receive pings from it.

File: src/protocol/libp2p/ping/mod.rs [hunk 2]
```diff
@@ -60,23 +60,32 @@ pub enum PingEvent {
...
 
-    /// Connected peers.
-    peers: HashSet<PeerId>,
+    /// Sinks we write Pings to.
+    outbound_sinks: HashMap<PeerId, SplitSink<Substream, Bytes>>,
 
-    /// Pending outbound substreams.
-    pending_outbound: FuturesUnordered<BoxFuture<'static, crate::Result<(PeerId, Duration)>>>,
+    /// Streams we read Pings from.
+    /// Keyed by a local counter to handle multiple streams per peer if necessary.
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]: As Dmitry [mentioned](https://github.com/paritytech/litep2p/pull/416#pullrequestreview-3360280764), there should be only one inbound ping substream per peer. Can we simplify this? I guess just using the `PeerId` like in `outbound_sinks`?

File: src/protocol/libp2p/ping/mod.rs [hunk 3]
```diff
@@ -24,26 +24,26 @@ use crate::{
...
 
 pub use config::{Config, ConfigBuilder};
-
 mod config;
 
 // TODO: https://github.com/paritytech/litep2p/issues/132 let the user handle max failures
 
 /// Log target for the file.
 const LOG_TARGET: &str = "litep2p::ipfs::ping";
+const PING_TIMEOUT: Duration = Duration::from_secs(10);
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]:
```suggestion
```

Since it is unused. However, we probably want to have a timeout for receiving pongs. Arguably out of scope for this PR though.

File: src/protocol/libp2p/ping/mod.rs [hunk 4]
```diff
@@ -85,126 +94,130 @@ impl Ping {
...
+                    }
                     Some(_) => {}
                     None => return,
                 },
-                _event = self.pending_inbound.next(), if !self.pending_inbound.is_empty() => {}
-                event = self.pending_outbound.next(), if !self.pending_outbound.is_empty() => {
+
+                _ = interval.tick() => {
+                    for (peer, sink) in self.outbound_sinks.iter_mut() {
+                        let payload = vec![0u8; 32];
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]: We should keep this `TODO` comment:

> `// TODO: https://github.com/paritytech/litep2p/issues/134 generate random payload and verify it`

File: src/protocol/libp2p/ping/mod.rs [hunk 5]
```diff
@@ -85,126 +94,130 @@ impl Ping {
...
+
+                        self.ping_times.insert(*peer, Instant::now());
+                        tracing::trace!(target: LOG_TARGET, ?peer, "sending ping");
+
+                        if let Err(error) = sink.send(Bytes::from(payload)).await {
+                             tracing::debug!(target: LOG_TARGET, ?peer, ?error, "failed to send ping");
+
+                        }
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]:
```suggestion
                        tracing::trace!(target: LOG_TARGET, ?peer, "sending ping");

                        if let Err(error) = sink.send(Bytes::from(payload)).await {
                             tracing::debug!(target: LOG_TARGET, ?peer, ?error, "failed to send ping");
                        } else {
                             self.ping_times.insert(*peer, Instant::now());
                        }
```

File: src/protocol/libp2p/ping/mod.rs [hunk 6]
```diff
@@ -85,126 +94,130 @@ impl Ping {
...
+                        Err(error) => {
+                            tracing::debug!(target: LOG_TARGET, ?peer, ?error, "ping substream closed/error");
+                            self.outbound_streams.remove(&peer);
+                            self.outbound_sinks.remove(&peer);
+                            self.ping_times.remove(&peer);
+                        }
+                    }
+                }
+
+                // Handle Outbound Responses (Ping is expected here)
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]:
```suggestion
                // Handle Inbound Pings
```

File: src/protocol/libp2p/ping/mod.rs [hunk 7]
```diff
@@ -85,126 +94,130 @@ impl Ping {
...
+                Some((id, event)) = self.inbound_streams.next() => {
+                    match event {
+                        Ok(payload) => {
+                             if let Some(sink) = self.inbound_sinks.get_mut(&id) {
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]: Consider logging when there's no sink for a peer ID.

File: src/protocol/libp2p/ping/mod.rs [hunk 8]
```diff
@@ -85,126 +94,130 @@ impl Ping {
...
+                                 tracing::trace!(target: LOG_TARGET, ?id, "sending pong");
+                                 if let Err(error) = sink.send(payload.freeze()).await {
+                                     tracing::debug!(target: LOG_TARGET, ?id, ?error, "failed to send pong");
+                                 }
+                             }
+                        }
+                        Err(_) => {
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]: Consider logging the error.

File: src/protocol/libp2p/ping/mod.rs [hunk 9]
```diff
@@ -85,126 +94,130 @@ impl Ping {
...
                     match event {
-                        Some(Ok((peer, elapsed))) => {
-                            let _ = self
-                                .tx
-                                .send(PingEvent::Ping {
-                                    peer,
-                                    ping: elapsed,
-                                })
-                                .await;
+                        Ok(payload) => {
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]:
```suggestion
                        Ok(_payload) => {
```

File: src/protocol/libp2p/ping/mod.rs [hunk 10]
```diff
@@ -24,26 +24,26 @@ use crate::{
     error::{Error, SubstreamError},
```
Comment (haikoschol) [inline src/protocol/libp2p/ping/mod.rs]:
```suggestion
```

**Review by haikoschol — COMMENTED** [review]
FWIW, I ran the following tests, using a litep2p listener and webrtc transport:

| Dialer | Listener -> Dialer Pings | Dialer -> Listener Pings |
|--------|---------------|----------------|
| [libp2p](https://github.com/haikoschol/webrtc-poc/tree/haiko-testing/client) |      ❌       |       ✅       |
| ["minimal smoldot env"](https://github.com/ChainSafe/smoldot/commits/haiko-libp2p-webrtc) | ✅ | ✅ |

The failing outbound pings with libp2p is an unrelated issue (#494).

File: src/transport/manager/mod.rs [hunk 11]
```diff
@@ -348,6 +348,7 @@ impl TransportManager {
             self.next_substream_id.clone(),
             self.transport_manager_handle.clone(),
             keep_alive_timeout,
+            true,
```
Comment (haikoschol) [inline src/transport/manager/mod.rs]: This should be `false` in case the protocol being registered is ping, right?

File: src/protocol/libp2p/ping/mod.rs (hunk 4 above)
Comment (haikoschol) [reply src/protocol/libp2p/ping/mod.rs]: @dharjeezy when I click on "Resolve comment", I get the error "Failed to resolve thread". Can you resolve it?

**Comment by dharjeezy** [comment]
@lexnv @haikoschol  @dmitry-markin  please help review

**Review by haikoschol — APPROVED** [review]

File: src/protocol/transport_service.rs [hunk 12]
```diff
@@ -298,6 +300,7 @@ impl TransportService {
         next_substream_id: Arc<AtomicUsize>,
         transport_handle: TransportManagerHandle,
         keep_alive_timeout: Duration,
+        counts_towards_keep_alive: bool,
```
Comment (haikoschol) [inline src/protocol/transport_service.rs]: @dharjeezy I just noticed that the addition of this parameter broke some tests:

```
litep2p$ cargo test --workspace

[...]

error[E0061]: this function takes 7 arguments but 6 arguments were supplied
    --> src/protocol/libp2p/kademlia/mod.rs:1287:40
     |
1287 |           let (transport_service, _tx) = TransportService::new(
     |  ________________________________________^^^^^^^^^^^^^^^^^^^^^-
1288 | |             peer,
1289 | |             ProtocolName::from("/kad/1"),
1290 | |             Vec::new(),
...    |
1293 | |             KEEP_ALIVE_TIMEOUT,
1294 | |         );
     | |_________- argument #7 of type `bool` is missing
     |
note: associated function defined here
    --> src/protocol/transport_service.rs:296:19
     |
 296 |     pub(crate) fn new(
     |                   ^^^
...
 303 |         counts_towards_keep_alive: bool,
     |         -------------------------------
help: provide the argument
     |
1287 |         let (transport_service, _tx) = TransportService::new(
 ...
1293 |             KEEP_ALIVE_TIMEOUT,
1294 ~             /* bool */,
1295 ~         );
     |

error[E0061]: this function takes 7 arguments but 6 arguments were supplied
   --> src/protocol/notification/tests/mod.rs:63:35
    |
 63 |       let (transport_service, tx) = TransportService::new(
    |  ___________________________________^^^^^^^^^^^^^^^^^^^^^-
 64 | |         peer,
 65 | |         ProtocolName::from("/notif/1"),
 66 | |         Vec::new(),
...   |
 69 | |         KEEP_ALIVE_TIMEOUT,
 70 | |     );
    | |_____- argument #7 of type `bool` is missing
    |
note: associated function defined here
   --> src/protocol/transport_service.rs:296:19
    |
296 |     pub(crate) fn new(
    |                   ^^^
...
303 |         counts_towards_keep_alive: bool,
    |         -------------------------------
help: provide the argument
    |
 63 |     let (transport_service, tx) = TransportService::new(
...
 69 |         KEEP_ALIVE_TIMEOUT,
 70 ~         /* bool */,
 71 ~     );
    |

error[E0061]: this function takes 7 arguments but 6 arguments were supplied
   --> src/protocol/request_response/tests.rs:61:35
    |
 61 |       let (transport_service, tx) = TransportService::new(
    |  ___________________________________^^^^^^^^^^^^^^^^^^^^^-
 62 | |         peer,
 63 | |         ProtocolName::from("/notif/1"),
 64 | |         Vec::new(),
...   |
 67 | |         KEEP_ALIVE_TIMEOUT,
 68 | |     );
    | |_____- argument #7 of type `bool` is missing
    |
note: associated function defined here
   --> src/protocol/transport_service.rs:296:19
    |
296 |     pub(crate) fn new(
    |                   ^^^
...
303 |         counts_towards_keep_alive: bool,
    |         -------------------------------
help: provide the argument
    |
 61 |     let (transport_service, tx) = TransportService::new(
...
 67 |         KEEP_ALIVE_TIMEOUT,
 68 ~         /* bool */,
 69 ~     );
    |

error[E0061]: this function takes 7 arguments but 6 arguments were supplied
   --> src/protocol/transport_service.rs:673:33
    |
673 |           let (service, sender) = TransportService::new(
    |  _________________________________^^^^^^^^^^^^^^^^^^^^^-
674 | |             peer,
675 | |             ProtocolName::from("/notif/1"),
676 | |             Vec::new(),
...   |
679 | |             KEEP_ALIVE_TIMEOUT,
680 | |         );
    | |_________- argument #7 of type `bool` is missing
    |
note: associated function defined here
   --> src/protocol/transport_service.rs:296:19
    |
296 |     pub(crate) fn new(
    |                   ^^^
...
303 |         counts_towards_keep_alive: bool,
    |         -------------------------------
help: provide the argument
    |
673 |         let (service, sender) = TransportService::new(
...
679 |             KEEP_ALIVE_TIMEOUT,
680 ~             /* bool */,
681 ~         );
    |

```

pls fix

Comment (haikoschol) [reply src/protocol/transport_service.rs]: @dharjeezy Thanks! Again, I can't resolve this for whatever reason. If you can, please do.

File: src/protocol/libp2p/ping/config.rs [hunk 13]
```diff
@@ -104,13 +117,19 @@ impl ConfigBuilder {
         self
     }
```
Comment (lexnv) [inline src/protocol/libp2p/ping/config.rs:119]: Nit: Is cargo doc check ignoring missings docs on public methods? We should also document this and state the defaults (same for above in public interfaces)

File: src/protocol/libp2p/ping/mod.rs [hunk 14]
```diff
@@ -85,93 +96,67 @@ impl Ping {
...
+
+        self.inbound_streams.insert(peer, stream);
+        self.inbound_sinks.insert(peer, sink);
     }
 
     /// Start [`Ping`] event loop.
     pub async fn run(mut self) {
         tracing::debug!(target: LOG_TARGET, "starting ping event loop");
 
+        let mut interval = tokio::time::interval(self.ping_interval);
```
Comment (lexnv) [inline src/protocol/libp2p/ping/mod.rs]: nit: This will get fired immediatelly, is this intended or should we disarm the first tick?

File: src/protocol/libp2p/ping/mod.rs [hunk 15]
```diff
@@ -185,26 +170,144 @@ impl Ping {
...
+                    let mut failed_outbound = Vec::new();
+
+                    for (peer, sink) in self.outbound_sinks.iter_mut() {
+                        // TODO: <https://github.com/paritytech/litep2p/issues/134>
+                        //       generate random payload and verify it.
+                        let payload = vec![0u8; 32];
+
+                        tracing::trace!(target: LOG_TARGET, ?peer, "sending ping");
+
+                        // Due to buggy implementation of ping protocol in litep2p before
```
Comment (lexnv) [inline src/protocol/libp2p/ping/mod.rs]: I would call it "Due to differences with older litep2p" since this was a decision made for simplicity i suppose

File: src/protocol/libp2p/ping/mod.rs [hunk 16]
```diff
@@ -185,26 +170,144 @@ impl Ping {
...
+                        // <https://github.com/paritytech/litep2p/pull/416>,
+                        // when talking to older litep2p we will:
+                        //  1. Successfully send first ping and receive pong.
+                        //  2. Successfully send second ping, but won't receive a response.
+                        //  3. Fail to send the third ping and reopen a substream, going to (1).
+                        //
+                        // Hence `trace` below.
+                        if let Err(error) = sink.send(Bytes::from(payload)).await {
```
Comment (lexnv) [inline src/protocol/libp2p/ping/mod.rs]: This could actually cause head of line blocking if the first peer is blocking. It might be worth fixing this since it could result under heavy load or malicious peers to delay sending the ping frames. Which then given a significant delay cause the remote to disconnect?

I would move this in a futures unordered

File: src/protocol/libp2p/ping/mod.rs [hunk 17]
```diff
@@ -185,26 +170,144 @@ impl Ping {
...
                                     ping: elapsed,
-                                })
-                                .await;
+                                }).await;
+                            }
+                        }
+                        Err(error) => {
+                            // `trace` because this is expected to happen with older versions of
+                            // litep2p.
+                            // TODO: why does this not happen in practice? Do we deliver substream
```
Comment (lexnv) [inline src/protocol/libp2p/ping/mod.rs]: Lets open an issue for this so we can investigate further

It looks like this invalidates the assumptions from interval tick above?

File: src/protocol/connection.rs [hunk 18]
```diff
@@ -158,7 +158,14 @@ impl ConnectionHandle {
     }
 }
 
-/// Type which allows the connection to be kept open.
+/// Type which allows to keep the connection opened and not allow the keep-alive mechanism to close
+/// it.
+///
+/// The [`Permit`] is created when beginning to open a substream and passed on until it reaches
+/// [`TransportService`](crate::protocol::TransportService), where the connection is upgraded (what
```
Comment (lexnv) [inline src/protocol/connection.rs]: nit: which

File: src/protocol/connection.rs [hunk 19]
```diff
@@ -158,7 +158,14 @@ impl ConnectionHandle {
...
+/// means it won't be closed) and the permit is not needed anymore and dropped.
+///
+/// Every use of a permit must be short-lived, make sure to drop it!
```
Comment (lexnv) [inline src/protocol/connection.rs]: nit: The permit is designed to be short-lived, please ensure this is dropped as soon as its no longer relevant

or similar

File: src/protocol/transport_service.rs [hunk 20]
```diff
@@ -287,6 +296,8 @@ pub struct TransportService {
 
     /// Close the connection if no substreams are open within this time frame.
     keep_alive_tracker: KeepAliveTracker,
+
```
Comment (lexnv) [inline src/protocol/transport_service.rs:307]: nit: Could add a tiny doc

File: src/protocol/transport_service.rs [hunk 21]
```diff
@@ -648,14 +667,21 @@ impl Stream for TransportService {
...
+                    {
                         self.keep_alive_tracker.substream_activity(peer, connection_id);
                         if let Some(context) = self.connections.get_mut(&peer) {
                             context.try_upgrade(&connection_id);
                         }
                     }
 
+                    // Connection is upgraded, we must now drop the permit.
+                    // This is for the reader, not for compiler.
+                    drop(permit);
```
Comment (lexnv) [inline src/protocol/transport_service.rs]: Could the try upgrade still fail now?

File: src/protocol/protocol_set.rs [hunk 22]
```diff
@@ -127,6 +127,10 @@ pub enum InnerTransportEvent {
 
         /// Substream.
         substream: Substream,
+
+        /// Permit that was held while this substream was opening. Must be dropped by
+        /// [`TransportService`](crate::protocol::TransportService) once connection is upgraded.
+        permit: Permit,
```
Comment (lexnv) [inline src/protocol/protocol_set.rs]: How I understand this:
- we decouple permits from substream
- whenever a substream is received we upgrade the connection (try_upgrade) which may also fail silently (but we hold the permit so that should be fine?)
- we are free to drop the permit
- the transport service checks periodically (5s) if a substream has been opened in this interval
- if no substreams were opened the connection is downgraded
- a downgraded connection is closed the moment the last substream exists (because it was previously holding permits)

Wouldn't this change "close on inactivity the connection once the last substream exists" to "close the connection immediately since all permits are dropped"?

File: src/protocol/libp2p/ping/config.rs (hunk 13 above)
Comment (dmitry-markin) [reply src/protocol/libp2p/ping/config.rs:119]: litep2p doesn't have `#![warn(missing_docs)]` set. But this is for another PR :)

File: src/protocol/libp2p/ping/mod.rs (hunk 14 above)
Comment (dmitry-markin) [reply src/protocol/libp2p/ping/mod.rs]: It's fine.

File: src/protocol/libp2p/ping/mod.rs (hunk 15 above)
Comment (dmitry-markin) [reply src/protocol/libp2p/ping/mod.rs]: It doesn't conform to the spec, so it's buggy)

File: src/protocol/libp2p/ping/mod.rs (hunk 16 above)
Comment (dmitry-markin) [reply src/protocol/libp2p/ping/mod.rs]: Yeah, was also thinking about it. Makes sense.

File: src/protocol/libp2p/ping/mod.rs (hunk 17 above)
Comment (dmitry-markin) [reply src/protocol/libp2p/ping/mod.rs]: > It looks like this invalidates the assumptions from interval tick above?

Why? `send()` in interval tick fails, while I would expect it to fail here if the substream reset events were delivered.

File: src/protocol/connection.rs (hunk 18 above)
Comment (haikoschol) [reply src/protocol/connection.rs]: "where" seems fine here. Or "which upgrades the connection".

File: src/protocol/protocol_set.rs (hunk 22 above)
Comment (dmitry-markin) [reply src/protocol/protocol_set.rs]: Yes, this is what makes me worry about Notifications substreams not keeping the connection open anymore.

May be there is a better way to not cause ping/identify substreams keep the connection open? I.e., `SubstreamKeepAlive::Yes` makes the substream store the permit, and `SubstreamKeepAlive::No` to drop it as soon as substream was opened? What do you think?

File: src/protocol/transport_service.rs (hunk 21 above)
Comment (dmitry-markin) [reply src/protocol/transport_service.rs]: No, because we are guaranteed to hold the valid permit.

File: src/protocol/protocol_set.rs (hunk 22 above)
Comment (lexnv) [reply src/protocol/protocol_set.rs]: Yep this approach looks good to me 🙏

Comment (dmitry-markin) [reply src/protocol/protocol_set.rs]: Done

File: src/protocol/libp2p/ping/mod.rs (hunk 16 above)
Comment (dmitry-markin) [reply src/protocol/libp2p/ping/mod.rs]: Done in https://github.com/paritytech/litep2p/pull/416/commits/b8d73cff66fc66c501b64661c88722fef4bedb37.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/a-deep-dive-into-overhauling-litep2ps-ping-protocol-to-support-periodic-pinging-spec-compliant-payloads-and-a-new-substreamkeepalive-mechanism-for-connection-lifecycle-management/17501/1
